### ISSUE TITLE
fatal error: mbedtls/base64.h: No such file or directory

### ISSUE THREAD

**Issue by antonioacademy10** [lucas-sesti/JWT_RS256#1]
Hello! Sorry to bother, I'm trying to use this library but I'm facing this issue 

**fatal error: mbedtls/base64.h: No such file or directory**

And I'm not sure where to find the mbedtls library as I didn't find it in the arduino library manager.

Thank you in advance

**Comment by lucas-sesti** [comment]
Hi! When i made this package, i was using ESP32... i dont know if Arduino has

**Comment by antonioacademy10** [comment]
Ok so I will try to use an ESP32, thank you for your time!

**Comment by antonioacademy10** [comment]
Closing as it's solved
